// Generated from the Payload schema; data copying runs between the schema phases.
export const createPages = [
  'CREATE TYPE "public"."enum_pages_blocks_overview_section_theme" AS ENUM(\'light\', \'dark\');',
  'CREATE TYPE "public"."enum_pages_blocks_overview_section_layout" AS ENUM(\'left\', \'right\');',
  'CREATE TYPE "public"."enum_pages_slug" AS ENUM(\'nutrition\', \'batchcooking\');',
  'CREATE TABLE "pages_blocks_hero_section_tags" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"label" varchar NOT NULL,\n\t"icon" varchar\n);\n',
  'CREATE TABLE "pages_blocks_hero_section_actions" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"label" varchar NOT NULL,\n\t"href" varchar NOT NULL\n);\n',
  'CREATE TABLE "pages_blocks_hero_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"image_id" integer,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "pages_blocks_overview_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"theme" "enum_pages_blocks_overview_section_theme" DEFAULT \'light\',\n\t"layout" "enum_pages_blocks_overview_section_layout" DEFAULT \'left\',\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "pages_blocks_issues_section_issues" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"icon" varchar,\n\t"issue" varchar,\n\t"description" varchar\n);\n',
  'CREATE TABLE "pages_blocks_issues_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"header" varchar,\n\t"solution_title" varchar,\n\t"solution_content" jsonb,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "pages_blocks_stepper_section_steps" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"title" varchar,\n\t"icon" varchar,\n\t"description" varchar\n);\n',
  'CREATE TABLE "pages_blocks_stepper_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "pages_blocks_pricing_section_plans_key_points" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"key_point" varchar\n);\n',
  'CREATE TABLE "pages_blocks_pricing_section_plans" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"recommended" boolean,\n\t"title" varchar,\n\t"description" varchar,\n\t"footer" varchar,\n\t"price" numeric,\n\t"final_price" numeric,\n\t"final_price_unit" varchar,\n\t"cta" varchar,\n\t"link" varchar\n);\n',
  'CREATE TABLE "pages_blocks_pricing_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" varchar,\n\t"footer" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "pages_blocks_info_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"media_id" integer,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "pages_blocks_testimonial_section_testimonials" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"name" varchar,\n\t"service" varchar,\n\t"content" varchar\n);\n',
  'CREATE TABLE "pages_blocks_testimonial_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "pages" (\n\t"id" serial PRIMARY KEY NOT NULL,\n\t"slug" "enum_pages_slug",\n\t"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n',
  'CREATE TABLE "pages_rels" (\n\t"id" serial PRIMARY KEY NOT NULL,\n\t"order" integer,\n\t"parent_id" integer NOT NULL,\n\t"path" varchar NOT NULL,\n\t"media_id" integer\n);\n',
  'ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "pages_id" integer;',
  'ALTER TABLE "pages_blocks_hero_section_tags" ADD CONSTRAINT "pages_blocks_hero_section_tags_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_hero_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_hero_section_actions" ADD CONSTRAINT "pages_blocks_hero_section_actions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_hero_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_hero_section" ADD CONSTRAINT "pages_blocks_hero_section_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_hero_section" ADD CONSTRAINT "pages_blocks_hero_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_overview_section" ADD CONSTRAINT "pages_blocks_overview_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_issues_section_issues" ADD CONSTRAINT "pages_blocks_issues_section_issues_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_issues_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_issues_section" ADD CONSTRAINT "pages_blocks_issues_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_stepper_section_steps" ADD CONSTRAINT "pages_blocks_stepper_section_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_stepper_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_stepper_section" ADD CONSTRAINT "pages_blocks_stepper_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_pricing_section_plans_key_points" ADD CONSTRAINT "pages_blocks_pricing_section_plans_key_points_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_pricing_section_plans"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_pricing_section_plans" ADD CONSTRAINT "pages_blocks_pricing_section_plans_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_pricing_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_pricing_section" ADD CONSTRAINT "pages_blocks_pricing_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_info_section" ADD CONSTRAINT "pages_blocks_info_section_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_info_section" ADD CONSTRAINT "pages_blocks_info_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_testimonial_section_testimonials" ADD CONSTRAINT "pages_blocks_testimonial_section_testimonials_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_testimonial_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_blocks_testimonial_section" ADD CONSTRAINT "pages_blocks_testimonial_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_media_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;',
  'CREATE INDEX "pages_blocks_hero_section_tags_order_idx" ON "pages_blocks_hero_section_tags" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_hero_section_tags_parent_id_idx" ON "pages_blocks_hero_section_tags" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_hero_section_actions_order_idx" ON "pages_blocks_hero_section_actions" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_hero_section_actions_parent_id_idx" ON "pages_blocks_hero_section_actions" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_hero_section_order_idx" ON "pages_blocks_hero_section" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_hero_section_parent_id_idx" ON "pages_blocks_hero_section" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_hero_section_path_idx" ON "pages_blocks_hero_section" USING btree ("_path");',
  'CREATE INDEX "pages_blocks_hero_section_image_idx" ON "pages_blocks_hero_section" USING btree ("image_id");',
  'CREATE INDEX "pages_blocks_overview_section_order_idx" ON "pages_blocks_overview_section" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_overview_section_parent_id_idx" ON "pages_blocks_overview_section" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_overview_section_path_idx" ON "pages_blocks_overview_section" USING btree ("_path");',
  'CREATE INDEX "pages_blocks_issues_section_issues_order_idx" ON "pages_blocks_issues_section_issues" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_issues_section_issues_parent_id_idx" ON "pages_blocks_issues_section_issues" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_issues_section_order_idx" ON "pages_blocks_issues_section" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_issues_section_parent_id_idx" ON "pages_blocks_issues_section" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_issues_section_path_idx" ON "pages_blocks_issues_section" USING btree ("_path");',
  'CREATE INDEX "pages_blocks_stepper_section_steps_order_idx" ON "pages_blocks_stepper_section_steps" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_stepper_section_steps_parent_id_idx" ON "pages_blocks_stepper_section_steps" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_stepper_section_order_idx" ON "pages_blocks_stepper_section" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_stepper_section_parent_id_idx" ON "pages_blocks_stepper_section" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_stepper_section_path_idx" ON "pages_blocks_stepper_section" USING btree ("_path");',
  'CREATE INDEX "pages_blocks_pricing_section_plans_key_points_order_idx" ON "pages_blocks_pricing_section_plans_key_points" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_pricing_section_plans_key_points_parent_id_idx" ON "pages_blocks_pricing_section_plans_key_points" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_pricing_section_plans_order_idx" ON "pages_blocks_pricing_section_plans" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_pricing_section_plans_parent_id_idx" ON "pages_blocks_pricing_section_plans" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_pricing_section_order_idx" ON "pages_blocks_pricing_section" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_pricing_section_parent_id_idx" ON "pages_blocks_pricing_section" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_pricing_section_path_idx" ON "pages_blocks_pricing_section" USING btree ("_path");',
  'CREATE INDEX "pages_blocks_info_section_order_idx" ON "pages_blocks_info_section" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_info_section_parent_id_idx" ON "pages_blocks_info_section" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_info_section_path_idx" ON "pages_blocks_info_section" USING btree ("_path");',
  'CREATE INDEX "pages_blocks_info_section_media_idx" ON "pages_blocks_info_section" USING btree ("media_id");',
  'CREATE INDEX "pages_blocks_testimonial_section_testimonials_order_idx" ON "pages_blocks_testimonial_section_testimonials" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_testimonial_section_testimonials_parent_id_idx" ON "pages_blocks_testimonial_section_testimonials" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_testimonial_section_order_idx" ON "pages_blocks_testimonial_section" USING btree ("_order");',
  'CREATE INDEX "pages_blocks_testimonial_section_parent_id_idx" ON "pages_blocks_testimonial_section" USING btree ("_parent_id");',
  'CREATE INDEX "pages_blocks_testimonial_section_path_idx" ON "pages_blocks_testimonial_section" USING btree ("_path");',
  'CREATE UNIQUE INDEX "pages_slug_idx" ON "pages" USING btree ("slug");',
  'CREATE INDEX "pages_updated_at_idx" ON "pages" USING btree ("updated_at");',
  'CREATE INDEX "pages_created_at_idx" ON "pages" USING btree ("created_at");',
  'CREATE INDEX "pages_rels_order_idx" ON "pages_rels" USING btree ("order");',
  'CREATE INDEX "pages_rels_parent_idx" ON "pages_rels" USING btree ("parent_id");',
  'CREATE INDEX "pages_rels_path_idx" ON "pages_rels" USING btree ("path");',
  'CREATE INDEX "pages_rels_media_id_idx" ON "pages_rels" USING btree ("media_id");',
  'ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;',
  'CREATE INDEX "payload_locked_documents_rels_pages_id_idx" ON "payload_locked_documents_rels" USING btree ("pages_id");',
]

export const dropGlobals = [
  'DROP TABLE "batchcooking_blocks_hero_section_tags" CASCADE;',
  'DROP TABLE "batchcooking_blocks_hero_section_actions" CASCADE;',
  'DROP TABLE "batchcooking_blocks_hero_section" CASCADE;',
  'DROP TABLE "batchcooking_blocks_overview_section" CASCADE;',
  'DROP TABLE "batchcooking_blocks_issues_section_issues" CASCADE;',
  'DROP TABLE "batchcooking_blocks_issues_section" CASCADE;',
  'DROP TABLE "batchcooking_blocks_stepper_section_steps" CASCADE;',
  'DROP TABLE "batchcooking_blocks_stepper_section" CASCADE;',
  'DROP TABLE "batchcooking_blocks_pricing_section_plans_key_points" CASCADE;',
  'DROP TABLE "batchcooking_blocks_pricing_section_plans" CASCADE;',
  'DROP TABLE "batchcooking_blocks_pricing_section" CASCADE;',
  'DROP TABLE "batchcooking_blocks_info_section" CASCADE;',
  'DROP TABLE "batchcooking_blocks_testimonial_section_testimonials" CASCADE;',
  'DROP TABLE "batchcooking_blocks_testimonial_section" CASCADE;',
  'DROP TABLE "batchcooking" CASCADE;',
  'DROP TABLE "batchcooking_rels" CASCADE;',
  'DROP TABLE "nutrition_blocks_hero_section_tags" CASCADE;',
  'DROP TABLE "nutrition_blocks_hero_section_actions" CASCADE;',
  'DROP TABLE "nutrition_blocks_hero_section" CASCADE;',
  'DROP TABLE "nutrition_blocks_overview_section" CASCADE;',
  'DROP TABLE "nutrition_blocks_issues_section_issues" CASCADE;',
  'DROP TABLE "nutrition_blocks_issues_section" CASCADE;',
  'DROP TABLE "nutrition_blocks_stepper_section_steps" CASCADE;',
  'DROP TABLE "nutrition_blocks_stepper_section" CASCADE;',
  'DROP TABLE "nutrition_blocks_pricing_section_plans_key_points" CASCADE;',
  'DROP TABLE "nutrition_blocks_pricing_section_plans" CASCADE;',
  'DROP TABLE "nutrition_blocks_pricing_section" CASCADE;',
  'DROP TABLE "nutrition_blocks_info_section" CASCADE;',
  'DROP TABLE "nutrition_blocks_testimonial_section_testimonials" CASCADE;',
  'DROP TABLE "nutrition_blocks_testimonial_section" CASCADE;',
  'DROP TABLE "nutrition" CASCADE;',
  'DROP TABLE "nutrition_rels" CASCADE;',
  'DROP TYPE "public"."enum_batchcooking_blocks_overview_section_theme";',
  'DROP TYPE "public"."enum_batchcooking_blocks_overview_section_layout";',
  'DROP TYPE "public"."enum_nutrition_blocks_overview_section_theme";',
  'DROP TYPE "public"."enum_nutrition_blocks_overview_section_layout";',
]

export const createGlobals = [
  'CREATE TYPE "public"."enum_batchcooking_blocks_overview_section_theme" AS ENUM(\'light\', \'dark\');',
  'CREATE TYPE "public"."enum_batchcooking_blocks_overview_section_layout" AS ENUM(\'left\', \'right\');',
  'CREATE TYPE "public"."enum_nutrition_blocks_overview_section_theme" AS ENUM(\'light\', \'dark\');',
  'CREATE TYPE "public"."enum_nutrition_blocks_overview_section_layout" AS ENUM(\'left\', \'right\');',
  'CREATE TABLE "batchcooking_blocks_hero_section_tags" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"label" varchar NOT NULL,\n\t"icon" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_hero_section_actions" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"label" varchar NOT NULL,\n\t"href" varchar NOT NULL\n);\n',
  'CREATE TABLE "batchcooking_blocks_hero_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"image_id" integer,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_overview_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"theme" "enum_batchcooking_blocks_overview_section_theme" DEFAULT \'light\',\n\t"layout" "enum_batchcooking_blocks_overview_section_layout" DEFAULT \'left\',\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_issues_section_issues" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"icon" varchar,\n\t"issue" varchar,\n\t"description" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_issues_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"header" varchar,\n\t"solution_title" varchar,\n\t"solution_content" jsonb,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_stepper_section_steps" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"title" varchar,\n\t"icon" varchar,\n\t"description" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_stepper_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_pricing_section_plans_key_points" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"key_point" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_pricing_section_plans" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"recommended" boolean,\n\t"title" varchar,\n\t"description" varchar,\n\t"footer" varchar,\n\t"price" numeric,\n\t"final_price" numeric,\n\t"final_price_unit" varchar,\n\t"cta" varchar,\n\t"link" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_pricing_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" varchar,\n\t"footer" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_info_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"media_id" integer,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_testimonial_section_testimonials" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"name" varchar,\n\t"service" varchar,\n\t"content" varchar\n);\n',
  'CREATE TABLE "batchcooking_blocks_testimonial_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "batchcooking" (\n\t"id" serial PRIMARY KEY NOT NULL,\n\t"updated_at" timestamp(3) with time zone,\n\t"created_at" timestamp(3) with time zone\n);\n',
  'CREATE TABLE "batchcooking_rels" (\n\t"id" serial PRIMARY KEY NOT NULL,\n\t"order" integer,\n\t"parent_id" integer NOT NULL,\n\t"path" varchar NOT NULL,\n\t"media_id" integer\n);\n',
  'CREATE TABLE "nutrition_blocks_hero_section_tags" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"label" varchar NOT NULL,\n\t"icon" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_hero_section_actions" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"label" varchar NOT NULL,\n\t"href" varchar NOT NULL\n);\n',
  'CREATE TABLE "nutrition_blocks_hero_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"image_id" integer,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_overview_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"theme" "enum_nutrition_blocks_overview_section_theme" DEFAULT \'light\',\n\t"layout" "enum_nutrition_blocks_overview_section_layout" DEFAULT \'left\',\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_issues_section_issues" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"icon" varchar,\n\t"issue" varchar,\n\t"description" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_issues_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"header" varchar,\n\t"solution_title" varchar,\n\t"solution_content" jsonb,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_stepper_section_steps" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"title" varchar,\n\t"icon" varchar,\n\t"description" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_stepper_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_pricing_section_plans_key_points" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"key_point" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_pricing_section_plans" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"recommended" boolean,\n\t"title" varchar,\n\t"description" varchar,\n\t"footer" varchar,\n\t"price" numeric,\n\t"final_price" numeric,\n\t"final_price_unit" varchar,\n\t"cta" varchar,\n\t"link" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_pricing_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" varchar,\n\t"footer" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_info_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"description" jsonb,\n\t"media_id" integer,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_testimonial_section_testimonials" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" varchar NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"name" varchar,\n\t"service" varchar,\n\t"content" varchar\n);\n',
  'CREATE TABLE "nutrition_blocks_testimonial_section" (\n\t"_order" integer NOT NULL,\n\t"_parent_id" integer NOT NULL,\n\t"_path" text NOT NULL,\n\t"id" varchar PRIMARY KEY NOT NULL,\n\t"section_id" varchar,\n\t"meta_title" varchar,\n\t"header" varchar,\n\t"block_name" varchar\n);\n',
  'CREATE TABLE "nutrition" (\n\t"id" serial PRIMARY KEY NOT NULL,\n\t"updated_at" timestamp(3) with time zone,\n\t"created_at" timestamp(3) with time zone\n);\n',
  'CREATE TABLE "nutrition_rels" (\n\t"id" serial PRIMARY KEY NOT NULL,\n\t"order" integer,\n\t"parent_id" integer NOT NULL,\n\t"path" varchar NOT NULL,\n\t"media_id" integer\n);\n',
  'ALTER TABLE "batchcooking_blocks_hero_section_tags" ADD CONSTRAINT "batchcooking_blocks_hero_section_tags_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking_blocks_hero_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_hero_section_actions" ADD CONSTRAINT "batchcooking_blocks_hero_section_actions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking_blocks_hero_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_hero_section" ADD CONSTRAINT "batchcooking_blocks_hero_section_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_hero_section" ADD CONSTRAINT "batchcooking_blocks_hero_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_overview_section" ADD CONSTRAINT "batchcooking_blocks_overview_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_issues_section_issues" ADD CONSTRAINT "batchcooking_blocks_issues_section_issues_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking_blocks_issues_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_issues_section" ADD CONSTRAINT "batchcooking_blocks_issues_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_stepper_section_steps" ADD CONSTRAINT "batchcooking_blocks_stepper_section_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking_blocks_stepper_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_stepper_section" ADD CONSTRAINT "batchcooking_blocks_stepper_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_pricing_section_plans_key_points" ADD CONSTRAINT "batchcooking_blocks_pricing_section_plans_key_points_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking_blocks_pricing_section_plans"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_pricing_section_plans" ADD CONSTRAINT "batchcooking_blocks_pricing_section_plans_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking_blocks_pricing_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_pricing_section" ADD CONSTRAINT "batchcooking_blocks_pricing_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_info_section" ADD CONSTRAINT "batchcooking_blocks_info_section_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_info_section" ADD CONSTRAINT "batchcooking_blocks_info_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_testimonial_section_testimonials" ADD CONSTRAINT "batchcooking_blocks_testimonial_section_testimonials_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking_blocks_testimonial_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_blocks_testimonial_section" ADD CONSTRAINT "batchcooking_blocks_testimonial_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_rels" ADD CONSTRAINT "batchcooking_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."batchcooking"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "batchcooking_rels" ADD CONSTRAINT "batchcooking_rels_media_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_hero_section_tags" ADD CONSTRAINT "nutrition_blocks_hero_section_tags_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition_blocks_hero_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_hero_section_actions" ADD CONSTRAINT "nutrition_blocks_hero_section_actions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition_blocks_hero_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_hero_section" ADD CONSTRAINT "nutrition_blocks_hero_section_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_hero_section" ADD CONSTRAINT "nutrition_blocks_hero_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_overview_section" ADD CONSTRAINT "nutrition_blocks_overview_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_issues_section_issues" ADD CONSTRAINT "nutrition_blocks_issues_section_issues_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition_blocks_issues_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_issues_section" ADD CONSTRAINT "nutrition_blocks_issues_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_stepper_section_steps" ADD CONSTRAINT "nutrition_blocks_stepper_section_steps_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition_blocks_stepper_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_stepper_section" ADD CONSTRAINT "nutrition_blocks_stepper_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_pricing_section_plans_key_points" ADD CONSTRAINT "nutrition_blocks_pricing_section_plans_key_points_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition_blocks_pricing_section_plans"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_pricing_section_plans" ADD CONSTRAINT "nutrition_blocks_pricing_section_plans_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition_blocks_pricing_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_pricing_section" ADD CONSTRAINT "nutrition_blocks_pricing_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_info_section" ADD CONSTRAINT "nutrition_blocks_info_section_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_info_section" ADD CONSTRAINT "nutrition_blocks_info_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_testimonial_section_testimonials" ADD CONSTRAINT "nutrition_blocks_testimonial_section_testimonials_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition_blocks_testimonial_section"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_blocks_testimonial_section" ADD CONSTRAINT "nutrition_blocks_testimonial_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_rels" ADD CONSTRAINT "nutrition_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."nutrition"("id") ON DELETE cascade ON UPDATE no action;',
  'ALTER TABLE "nutrition_rels" ADD CONSTRAINT "nutrition_rels_media_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;',
  'CREATE INDEX "batchcooking_blocks_hero_section_tags_order_idx" ON "batchcooking_blocks_hero_section_tags" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_hero_section_tags_parent_id_idx" ON "batchcooking_blocks_hero_section_tags" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_hero_section_actions_order_idx" ON "batchcooking_blocks_hero_section_actions" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_hero_section_actions_parent_id_idx" ON "batchcooking_blocks_hero_section_actions" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_hero_section_order_idx" ON "batchcooking_blocks_hero_section" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_hero_section_parent_id_idx" ON "batchcooking_blocks_hero_section" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_hero_section_path_idx" ON "batchcooking_blocks_hero_section" USING btree ("_path");',
  'CREATE INDEX "batchcooking_blocks_hero_section_image_idx" ON "batchcooking_blocks_hero_section" USING btree ("image_id");',
  'CREATE INDEX "batchcooking_blocks_overview_section_order_idx" ON "batchcooking_blocks_overview_section" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_overview_section_parent_id_idx" ON "batchcooking_blocks_overview_section" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_overview_section_path_idx" ON "batchcooking_blocks_overview_section" USING btree ("_path");',
  'CREATE INDEX "batchcooking_blocks_issues_section_issues_order_idx" ON "batchcooking_blocks_issues_section_issues" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_issues_section_issues_parent_id_idx" ON "batchcooking_blocks_issues_section_issues" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_issues_section_order_idx" ON "batchcooking_blocks_issues_section" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_issues_section_parent_id_idx" ON "batchcooking_blocks_issues_section" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_issues_section_path_idx" ON "batchcooking_blocks_issues_section" USING btree ("_path");',
  'CREATE INDEX "batchcooking_blocks_stepper_section_steps_order_idx" ON "batchcooking_blocks_stepper_section_steps" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_stepper_section_steps_parent_id_idx" ON "batchcooking_blocks_stepper_section_steps" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_stepper_section_order_idx" ON "batchcooking_blocks_stepper_section" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_stepper_section_parent_id_idx" ON "batchcooking_blocks_stepper_section" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_stepper_section_path_idx" ON "batchcooking_blocks_stepper_section" USING btree ("_path");',
  'CREATE INDEX "batchcooking_blocks_pricing_section_plans_key_points_order_idx" ON "batchcooking_blocks_pricing_section_plans_key_points" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_pricing_section_plans_key_points_parent_id_idx" ON "batchcooking_blocks_pricing_section_plans_key_points" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_pricing_section_plans_order_idx" ON "batchcooking_blocks_pricing_section_plans" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_pricing_section_plans_parent_id_idx" ON "batchcooking_blocks_pricing_section_plans" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_pricing_section_order_idx" ON "batchcooking_blocks_pricing_section" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_pricing_section_parent_id_idx" ON "batchcooking_blocks_pricing_section" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_pricing_section_path_idx" ON "batchcooking_blocks_pricing_section" USING btree ("_path");',
  'CREATE INDEX "batchcooking_blocks_info_section_order_idx" ON "batchcooking_blocks_info_section" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_info_section_parent_id_idx" ON "batchcooking_blocks_info_section" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_info_section_path_idx" ON "batchcooking_blocks_info_section" USING btree ("_path");',
  'CREATE INDEX "batchcooking_blocks_info_section_media_idx" ON "batchcooking_blocks_info_section" USING btree ("media_id");',
  'CREATE INDEX "batchcooking_blocks_testimonial_section_testimonials_order_idx" ON "batchcooking_blocks_testimonial_section_testimonials" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_testimonial_section_testimonials_parent_id_idx" ON "batchcooking_blocks_testimonial_section_testimonials" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_testimonial_section_order_idx" ON "batchcooking_blocks_testimonial_section" USING btree ("_order");',
  'CREATE INDEX "batchcooking_blocks_testimonial_section_parent_id_idx" ON "batchcooking_blocks_testimonial_section" USING btree ("_parent_id");',
  'CREATE INDEX "batchcooking_blocks_testimonial_section_path_idx" ON "batchcooking_blocks_testimonial_section" USING btree ("_path");',
  'CREATE INDEX "batchcooking_rels_order_idx" ON "batchcooking_rels" USING btree ("order");',
  'CREATE INDEX "batchcooking_rels_parent_idx" ON "batchcooking_rels" USING btree ("parent_id");',
  'CREATE INDEX "batchcooking_rels_path_idx" ON "batchcooking_rels" USING btree ("path");',
  'CREATE INDEX "batchcooking_rels_media_id_idx" ON "batchcooking_rels" USING btree ("media_id");',
  'CREATE INDEX "nutrition_blocks_hero_section_tags_order_idx" ON "nutrition_blocks_hero_section_tags" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_hero_section_tags_parent_id_idx" ON "nutrition_blocks_hero_section_tags" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_hero_section_actions_order_idx" ON "nutrition_blocks_hero_section_actions" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_hero_section_actions_parent_id_idx" ON "nutrition_blocks_hero_section_actions" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_hero_section_order_idx" ON "nutrition_blocks_hero_section" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_hero_section_parent_id_idx" ON "nutrition_blocks_hero_section" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_hero_section_path_idx" ON "nutrition_blocks_hero_section" USING btree ("_path");',
  'CREATE INDEX "nutrition_blocks_hero_section_image_idx" ON "nutrition_blocks_hero_section" USING btree ("image_id");',
  'CREATE INDEX "nutrition_blocks_overview_section_order_idx" ON "nutrition_blocks_overview_section" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_overview_section_parent_id_idx" ON "nutrition_blocks_overview_section" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_overview_section_path_idx" ON "nutrition_blocks_overview_section" USING btree ("_path");',
  'CREATE INDEX "nutrition_blocks_issues_section_issues_order_idx" ON "nutrition_blocks_issues_section_issues" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_issues_section_issues_parent_id_idx" ON "nutrition_blocks_issues_section_issues" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_issues_section_order_idx" ON "nutrition_blocks_issues_section" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_issues_section_parent_id_idx" ON "nutrition_blocks_issues_section" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_issues_section_path_idx" ON "nutrition_blocks_issues_section" USING btree ("_path");',
  'CREATE INDEX "nutrition_blocks_stepper_section_steps_order_idx" ON "nutrition_blocks_stepper_section_steps" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_stepper_section_steps_parent_id_idx" ON "nutrition_blocks_stepper_section_steps" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_stepper_section_order_idx" ON "nutrition_blocks_stepper_section" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_stepper_section_parent_id_idx" ON "nutrition_blocks_stepper_section" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_stepper_section_path_idx" ON "nutrition_blocks_stepper_section" USING btree ("_path");',
  'CREATE INDEX "nutrition_blocks_pricing_section_plans_key_points_order_idx" ON "nutrition_blocks_pricing_section_plans_key_points" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_pricing_section_plans_key_points_parent_id_idx" ON "nutrition_blocks_pricing_section_plans_key_points" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_pricing_section_plans_order_idx" ON "nutrition_blocks_pricing_section_plans" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_pricing_section_plans_parent_id_idx" ON "nutrition_blocks_pricing_section_plans" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_pricing_section_order_idx" ON "nutrition_blocks_pricing_section" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_pricing_section_parent_id_idx" ON "nutrition_blocks_pricing_section" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_pricing_section_path_idx" ON "nutrition_blocks_pricing_section" USING btree ("_path");',
  'CREATE INDEX "nutrition_blocks_info_section_order_idx" ON "nutrition_blocks_info_section" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_info_section_parent_id_idx" ON "nutrition_blocks_info_section" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_info_section_path_idx" ON "nutrition_blocks_info_section" USING btree ("_path");',
  'CREATE INDEX "nutrition_blocks_info_section_media_idx" ON "nutrition_blocks_info_section" USING btree ("media_id");',
  'CREATE INDEX "nutrition_blocks_testimonial_section_testimonials_order_idx" ON "nutrition_blocks_testimonial_section_testimonials" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_testimonial_section_testimonials_parent_id_idx" ON "nutrition_blocks_testimonial_section_testimonials" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_testimonial_section_order_idx" ON "nutrition_blocks_testimonial_section" USING btree ("_order");',
  'CREATE INDEX "nutrition_blocks_testimonial_section_parent_id_idx" ON "nutrition_blocks_testimonial_section" USING btree ("_parent_id");',
  'CREATE INDEX "nutrition_blocks_testimonial_section_path_idx" ON "nutrition_blocks_testimonial_section" USING btree ("_path");',
  'CREATE INDEX "nutrition_rels_order_idx" ON "nutrition_rels" USING btree ("order");',
  'CREATE INDEX "nutrition_rels_parent_idx" ON "nutrition_rels" USING btree ("parent_id");',
  'CREATE INDEX "nutrition_rels_path_idx" ON "nutrition_rels" USING btree ("path");',
  'CREATE INDEX "nutrition_rels_media_id_idx" ON "nutrition_rels" USING btree ("media_id");',
]

export const dropPages = [
  'ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_pages_fk";',
  'ALTER TABLE "pages_blocks_hero_section_tags" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_hero_section_actions" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_hero_section" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_overview_section" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_issues_section_issues" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_issues_section" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_stepper_section_steps" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_stepper_section" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_pricing_section_plans_key_points" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_pricing_section_plans" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_pricing_section" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_info_section" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_testimonial_section_testimonials" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_blocks_testimonial_section" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages" DISABLE ROW LEVEL SECURITY;',
  'ALTER TABLE "pages_rels" DISABLE ROW LEVEL SECURITY;',
  'DROP TABLE "pages_blocks_hero_section_tags" CASCADE;',
  'DROP TABLE "pages_blocks_hero_section_actions" CASCADE;',
  'DROP TABLE "pages_blocks_hero_section" CASCADE;',
  'DROP TABLE "pages_blocks_overview_section" CASCADE;',
  'DROP TABLE "pages_blocks_issues_section_issues" CASCADE;',
  'DROP TABLE "pages_blocks_issues_section" CASCADE;',
  'DROP TABLE "pages_blocks_stepper_section_steps" CASCADE;',
  'DROP TABLE "pages_blocks_stepper_section" CASCADE;',
  'DROP TABLE "pages_blocks_pricing_section_plans_key_points" CASCADE;',
  'DROP TABLE "pages_blocks_pricing_section_plans" CASCADE;',
  'DROP TABLE "pages_blocks_pricing_section" CASCADE;',
  'DROP TABLE "pages_blocks_info_section" CASCADE;',
  'DROP TABLE "pages_blocks_testimonial_section_testimonials" CASCADE;',
  'DROP TABLE "pages_blocks_testimonial_section" CASCADE;',
  'DROP TABLE "pages" CASCADE;',
  'DROP TABLE "pages_rels" CASCADE;',
  'DROP INDEX "payload_locked_documents_rels_pages_id_idx";',
  'ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "pages_id";',
  'DROP TYPE "public"."enum_pages_blocks_overview_section_theme";',
  'DROP TYPE "public"."enum_pages_blocks_overview_section_layout";',
  'DROP TYPE "public"."enum_pages_slug";',
]
