/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    'hero-section': HeroSection;
    'overview-section': OverviewSection;
    'issues-section': IssuesSection;
    'stepper-section': StepperSection;
    'pricing-section': PricingSection;
    'info-section': InfoSection;
    'testimonial-section': TestimonialSection;
  };
  collections: {
    users: User;
    media: Media;
    offers: Offer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    batchcooking: Batchcooking;
    nutrition: Nutrition;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    batchcooking: BatchcookingSelect<false> | BatchcookingSelect<true>;
    nutrition: NutritionSelect<false> | NutritionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section".
 */
export interface HeroSection {
  tags?:
    | {
        label: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  header?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  actions?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "overview-section".
 */
export interface OverviewSection {
  'meta-title'?: string | null;
  header?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?: (number | Media)[] | null;
  theme?: ('light' | 'dark') | null;
  layout?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'overview-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issues-section".
 */
export interface IssuesSection {
  header?: string | null;
  issues?:
    | {
        icon?: string | null;
        issue?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  'solution-title'?: string | null;
  'solution-content'?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'issues-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stepper-section".
 */
export interface StepperSection {
  'meta-title'?: string | null;
  header?: string | null;
  description?: string | null;
  steps?:
    | {
        title?: string | null;
        icon?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stepper-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-section".
 */
export interface PricingSection {
  'meta-title'?: string | null;
  header?: string | null;
  description?: string | null;
  plans?:
    | {
        recommended?: boolean | null;
        title?: string | null;
        description?: string | null;
        footer?: string | null;
        'key-points'?:
          | {
              'key-point'?: string | null;
              id?: string | null;
            }[]
          | null;
        price?: number | null;
        'final-price'?: number | null;
        'final-price-unit'?: string | null;
        cta?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  footer?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "info-section".
 */
export interface InfoSection {
  'meta-title'?: string | null;
  header?: string | null;
  description?: string | null;
  media?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'info-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial-section".
 */
export interface TestimonialSection {
  'meta-title'?: string | null;
  header?: string | null;
  testimonials?:
    | {
        name?: string | null;
        service?: string | null;
        content?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  price: number;
  quantity?: string | null;
  description: string;
  /**
   * Texte affiché en bas de la carte d'offre pour les offres moins mises en avant. Laissez vide si non utilisé.
   */
  disclaimer?: string | null;
  features: {
    feature: string;
    id?: string | null;
  }[];
  /**
   * URL externe pour réserver cette offre (ex: lien Calendly)
   */
  bookingLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  price?: T;
  quantity?: T;
  description?: T;
  disclaimer?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  bookingLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  'batchcooking-image'?: (number | null) | Media;
  'batchcooking-title'?: string | null;
  'batchcooking-description'?: string | null;
  'nutrition-image'?: (number | null) | Media;
  'nutrition-title'?: string | null;
  'nutrition-description'?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batchcooking".
 */
export interface Batchcooking {
  id: number;
  sections?:
    | (
        | {
            tags?:
              | {
                  label: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            header?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            actions?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            images?: (number | Media)[] | null;
            theme?: ('light' | 'dark') | null;
            layout?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'overview-section';
          }
        | {
            header?: string | null;
            issues?:
              | {
                  icon?: string | null;
                  issue?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            'solution-title'?: string | null;
            'solution-content'?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'issues-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: string | null;
            steps?:
              | {
                  title?: string | null;
                  icon?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepper-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: string | null;
            plans?:
              | {
                  recommended?: boolean | null;
                  title?: string | null;
                  description?: string | null;
                  footer?: string | null;
                  'key-points'?:
                    | {
                        'key-point'?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  price?: number | null;
                  'final-price'?: number | null;
                  'final-price-unit'?: string | null;
                  cta?: string | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            footer?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: string | null;
            media?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'info-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            testimonials?:
              | {
                  name?: string | null;
                  service?: string | null;
                  content?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial-section';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nutrition".
 */
export interface Nutrition {
  id: number;
  sections?:
    | (
        | {
            tags?:
              | {
                  label: string;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            header?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image?: (number | null) | Media;
            actions?:
              | {
                  label: string;
                  href: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            images?: (number | Media)[] | null;
            theme?: ('light' | 'dark') | null;
            layout?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'overview-section';
          }
        | {
            header?: string | null;
            issues?:
              | {
                  icon?: string | null;
                  issue?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            'solution-title'?: string | null;
            'solution-content'?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'issues-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: string | null;
            steps?:
              | {
                  title?: string | null;
                  icon?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepper-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: string | null;
            plans?:
              | {
                  recommended?: boolean | null;
                  title?: string | null;
                  description?: string | null;
                  footer?: string | null;
                  'key-points'?:
                    | {
                        'key-point'?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  price?: number | null;
                  'final-price'?: number | null;
                  'final-price-unit'?: string | null;
                  cta?: string | null;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            footer?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            description?: string | null;
            media?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'info-section';
          }
        | {
            'meta-title'?: string | null;
            header?: string | null;
            testimonials?:
              | {
                  name?: string | null;
                  service?: string | null;
                  content?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonial-section';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  'batchcooking-image'?: T;
  'batchcooking-title'?: T;
  'batchcooking-description'?: T;
  'nutrition-image'?: T;
  'nutrition-title'?: T;
  'nutrition-description'?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batchcooking_select".
 */
export interface BatchcookingSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        'hero-section'?:
          | T
          | {
              tags?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              header?: T;
              description?: T;
              image?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'overview-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              images?: T;
              theme?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        'issues-section'?:
          | T
          | {
              header?: T;
              issues?:
                | T
                | {
                    icon?: T;
                    issue?: T;
                    description?: T;
                    id?: T;
                  };
              'solution-title'?: T;
              'solution-content'?: T;
              id?: T;
              blockName?: T;
            };
        'stepper-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              steps?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pricing-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              plans?:
                | T
                | {
                    recommended?: T;
                    title?: T;
                    description?: T;
                    footer?: T;
                    'key-points'?:
                      | T
                      | {
                          'key-point'?: T;
                          id?: T;
                        };
                    price?: T;
                    'final-price'?: T;
                    'final-price-unit'?: T;
                    cta?: T;
                    link?: T;
                    id?: T;
                  };
              footer?: T;
              id?: T;
              blockName?: T;
            };
        'info-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        'testimonial-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    service?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nutrition_select".
 */
export interface NutritionSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        'hero-section'?:
          | T
          | {
              tags?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              header?: T;
              description?: T;
              image?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'overview-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              images?: T;
              theme?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        'issues-section'?:
          | T
          | {
              header?: T;
              issues?:
                | T
                | {
                    icon?: T;
                    issue?: T;
                    description?: T;
                    id?: T;
                  };
              'solution-title'?: T;
              'solution-content'?: T;
              id?: T;
              blockName?: T;
            };
        'stepper-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              steps?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'pricing-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              plans?:
                | T
                | {
                    recommended?: T;
                    title?: T;
                    description?: T;
                    footer?: T;
                    'key-points'?:
                      | T
                      | {
                          'key-point'?: T;
                          id?: T;
                        };
                    price?: T;
                    'final-price'?: T;
                    'final-price-unit'?: T;
                    cta?: T;
                    link?: T;
                    id?: T;
                  };
              footer?: T;
              id?: T;
              blockName?: T;
            };
        'info-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              description?: T;
              media?: T;
              id?: T;
              blockName?: T;
            };
        'testimonial-section'?:
          | T
          | {
              'meta-title'?: T;
              header?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    service?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}